#! /usr/bin/env sh

# File to test
EXP_SCRIPT="substitution.py"

# Text colors
COLOR_REST="$(tput sgr0)"
COLOR_RED="$(tput setaf 1)"
COLOR_GREEN="$(tput setaf 2)"

# Test counters
NB_TEST_OK=0
NB_TEST_TOTAL=0

##################################################
# check command line params
##################################################
GIVEN_SCRIPT=""
if [ $# -eq 1 ]
then
    GIVEN_SCRIPT="${1}"
else
    printf "Give the script name in command line\n"
    exit
fi

##################################################
# Check if python is available
##################################################
pyapp=`which python`
if [ "${pyapp:0:1}" == "/" ]
then
    python --version
else
    printf "Python not found\n"
    exit
fi

##################################################
# Check if the script has been given
##################################################
if [ "${GIVEN_SCRIPT}" != "${EXP_SCRIPT}" ]
then
    printf "Give the script name in command line\n"
    exit
fi

##################################################
# Check if the given script exists
##################################################
if [ ! -f "${EXP_SCRIPT}" ]
then
    printf "File not found: ${EXP_SCRIPT}\n"
    exit
fi

##################################################
# Test function
##################################################
run_test () {
    TEST_NAME=$1
    TEST_NUM=$2
    TEST_ARG=$3
    TEST_IN=.test/${TEST_NUM}.in
    TEST_EXP=.test/${TEST_NUM}.exp
    TEST_OUT=".test/${TEST_NUM}_test.out"
    TEST_DIFF=".test/${TEST_NUM}_test.diff"
    python ${EXP_SCRIPT} ${TEST_ARG} < ${TEST_IN}  > ${TEST_OUT}
    diff ${TEST_EXP} ${TEST_OUT} > ${TEST_DIFF}
    NB_DIFF=`cat ${TEST_DIFF} | wc -l`
    NB_TEST_TOTAL=$((NB_TEST_TOTAL+1))
    if [ ${NB_DIFF} -eq 0 ]
    then
        printf "${TEST_NUM} ${COLOR_GREEN}\xE2\x9C\x94${COLOR_REST} ${TEST_NAME}\n"
        rm ${TEST_OUT}
        rm ${TEST_DIFF}
        NB_TEST_OK=$((NB_TEST_OK+1))
    else
        printf "\n"
        printf "${TEST_NUM} ${COLOR_RED}\xE2\x9C\x97${COLOR_REST} ${TEST_NAME}\n"
        printf "./${EXP_SCRIPT} ${TEST_ARG} < ${TEST_IN}  > ${TEST_OUT}\n"
        printf "${COLOR_GREEN}Expected${COLOR_REST}\n"
        grep "<" ${TEST_DIFF}
        printf "${COLOR_RED}Given${COLOR_REST}\n"
        grep ">" ${TEST_DIFF}
        printf "\n"
    fi
}

##################################################
# Run tests
##################################################
run_test "Substitution 01" "01" ".test/01.in AZERTYUIOPQSDFGHJKLMWXCVBN"
run_test "Substitution 02" "02" ".test/02.in AZERTYUIOPQSDFGHJKLMWXCVBN"
run_test "Substitution 03" "03" ".test/03.in MLKJHGFDSQNBVCXWPOIUYTREZA"
run_test "Substitution 04" "04" ".test/04.in MLKJHGFDSQNBVCXWPOIUYTREZA"
run_test "Substitution 05" "05" ".test/05.in GFDSQTREZABVCXWPOIUYMLKJHN"
run_test "Substitution 06 - empty command line" "06" ""
run_test "Substitution 07 - no key" "07" ".test/07.in"
run_test "Substitution 08 - small alphabet" "08" ".test/08.in SQNBUYTR"
run_test "Substitution 09 - repeats in alphabet" "09" ".test/09.in GFDSQTREZABGCXWPOIUYMHKJHN"
run_test "Substitution 10 - key first instead of file" "10" "AZERTYUIOPQSDFGHJKLMWXCVBN .test/09.in"
run_test "Substitution 11" "11" ".test/11.in MLKJHGFDSQNBVCXWPOIUYTREZA -r"
run_test "Substitution 12" "12" ".test/12.in GFDSQTREZABVCXWPOIUYMLKJHN -r"

##################################################
# Print Summary
##################################################
if [ ${NB_TEST_OK} -eq ${NB_TEST_TOTAL} ]
then
    printf "Validated: ${COLOR_GREEN}${NB_TEST_OK}/${NB_TEST_TOTAL}${COLOR_REST}\n"
else
    printf "Validated: ${COLOR_RED}${NB_TEST_OK}/${NB_TEST_TOTAL}${COLOR_REST}\n"
fi
